### ISSUE TITLE
Provide flag to disable automatic dependency processing

### ISSUE THREAD

**Issue by ChrisEineke** [panitw/easy-rpm#25]
Could we introduce a flag to disable automatic dependency processing: http://www.rpm.org/max-rpm/s1-rpm-inside-tags.html#S3-RPM-INSIDE-AUTOREQPROV-TAG

**Comment by tspires** [comment]
I am using this flag, I don't think it's working. I'm still getting a lot of dependencies picked up by the build. Maybe I don't understand RPM dependencies well enough. But the rpm process is scanning scripts and picking up hashbang executables and adding them as dependencies.

**Comment by ceineke** [comment]
You can set ```autoReqProv``` to ```false``` to disable automatic dependency scanning.
