### ISSUE TITLE
Documentation around native add-ons

### ISSUE THREAD

**Issue by majgis** [panitw/easy-rpm#70]
It would be helpful to add a note in the readme about native add-ons and setting autoReq, autoProv to false.

Before setting these flags to false, these unnecessary items were in the RPM:

```
Provides:      node_expat.node()(64bit)  

Requires:      /usr/bin/env  
Requires:      /usr/bin/perl  
Requires:      libc.so.6()(64bit)  
Requires:      libc.so.6(GLIBC_2.2.5)(64bit)  
Requires:      libgcc_s.so.1()(64bit)  
Requires:      libm.so.6()(64bit)  
Requires:      libpthread.so.0()(64bit)  
Requires:      libstdc++.so.6()(64bit)  
Requires:      libstdc++.so.6(GLIBCXX_3.4)(64bit)  
Requires:      perl(IO::Handle)  
Requires:      perl(IPC::Open3)  
Requires:      perl(Symbol)  
Requires:      perl(Test::More)  
Requires:      perl(strict)  
Requires:      perl(warnings)  
```

**Comment by paulcoyle** [comment]
The additional requirements added to the RPM spec file are generated by `rpmbuild` and so will vary depending on what is being added ([see here for more info](http://www.rpm.org/max-rpm-snapshot/s1-rpm-depend-auto-depend.html)).  So basically, if those flags are not set to false, `rpmbuild` is doing what it is supposed to.  Given this, what exactly should we be informing the user of in the README?

**Comment by majgis** [comment]
`Note: If you are building native-addons, rpmbuild will add several require statements that you probably don't need.  Consider setting autoReq, autoProv to false.`

For some of us, this is our first experience building RPMs, and it is not obvious from that documentation that native-addons will add a bunch of cruft to your RPM. How your tool interacts with Node.js modules seems relevant to Node.js based tool.

**Comment by paulcoyle** [comment]
Makes sense.  Open a PR with that note in the README (maybe in the "Overview" section).  You could also link the `autoReq` and `autoProv` to the documented sections in the README as well.
