### ISSUE TITLE
add support for Obsolete tag

### ISSUE THREAD

**Issue by opnet** [panitw/easy-rpm#79]
The dependencies section of the spec file appears to have `requires`, `provides`, and `conflicts` but nothing for obsoletes. I recommend introducing the tag following the same syntax as the other tags easy-rpm already provides:

```
options: {
    obsoletes: [ "foo-bar >= 1.12", "some-package" ]
}
```

**Comment by paulcoyle** [comment]
Thanks for this and your PR.  I've merged this into the develop stream and will be cutting a new release fairly soon.
